import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    appName: 'e-vizza',
    tagline: 'Your trusted visa assistance partner',
    legalNotice: 'This platform provides independent visa assistance services and is not affiliated with any government authority.',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    nationality: 'Nationality',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    newApplication: 'New Application',
    myApplications: 'My Applications',
    selectCountry: 'Select Destination Country',
    selectVisaType: 'Select Visa Type',
    uploadDocuments: 'Upload Documents',
    submit: 'Submit Application',
    cancel: 'Cancel',
    next: 'Next',
    back: 'Back',
    status: 'Status',
    applicationNumber: 'Application Number',
    submittedDate: 'Submitted Date',
    viewDetails: 'View Details',
    draft: 'Draft',
    submitted: 'Submitted',
    awaiting_payment: 'Awaiting Payment',
    payment_confirmed: 'Payment Confirmed',
    processing: 'Processing',
    documents_prepared: 'Documents Prepared',
    submitted_to_embassy: 'Submitted to Embassy',
    approved: 'Approved',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    urgent: 'Urgent Processing',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAsRead: 'Mark as read',
    admin: 'Admin Panel',
    allApplications: 'All Applications',
    pendingReview: 'Pending Review',
    awaitingPayment: 'Awaiting Payment',
    inProgress: 'In Progress',
    completed: 'Completed',
    reviewApplication: 'Review Application',
    confirmPayment: 'Confirm Payment',
    updateStatus: 'Update Status',
    addNotes: 'Add Notes',
    verifyDocuments: 'Verify Documents',
    approve: 'Approve',
    reject: 'Reject',
    downloadDocuments: 'Download Documents',
    applicantInfo: 'Applicant Information',
    travelInfo: 'Travel Information',
    documents: 'Documents',
    statusHistory: 'Status History',
    required: 'Required',
    optional: 'Optional',
    uploadFile: 'Upload File',
    fileUploaded: 'File Uploaded',
    remove: 'Remove',
    language: 'Language',
    profile: 'Profile',
    settings: 'Settings',
    save: 'Save',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    saudiArabia: 'Saudi Arabia',
    indonesia: 'Indonesia',
    umrahVisa: 'Umrah Visa',
    visitVisa: 'Visit Visa',
    eVisa: 'eVisa',
  },
  fr: {
    appName: 'e-vizza',
    tagline: 'Votre partenaire de confiance pour l\'assistance visa',
    legalNotice: 'Cette plateforme fournit des services d\'assistance visa indépendants et n\'est affiliée à aucune autorité gouvernementale.',
    signIn: 'Se Connecter',
    signUp: 'S\'inscrire',
    signOut: 'Se Déconnecter',
    email: 'Email',
    password: 'Mot de passe',
    fullName: 'Nom Complet',
    phone: 'Numéro de Téléphone',
    nationality: 'Nationalité',
    createAccount: 'Créer un Compte',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    dontHaveAccount: "Vous n'avez pas de compte?",
    welcome: 'Bienvenue',
    dashboard: 'Tableau de Bord',
    newApplication: 'Nouvelle Demande',
    myApplications: 'Mes Demandes',
    selectCountry: 'Sélectionner le Pays de Destination',
    selectVisaType: 'Sélectionner le Type de Visa',
    uploadDocuments: 'Télécharger les Documents',
    submit: 'Soumettre la Demande',
    cancel: 'Annuler',
    next: 'Suivant',
    back: 'Retour',
    status: 'Statut',
    applicationNumber: 'Numéro de Demande',
    submittedDate: 'Date de Soumission',
    viewDetails: 'Voir les Détails',
    draft: 'Brouillon',
    submitted: 'Soumis',
    awaiting_payment: 'En Attente de Paiement',
    payment_confirmed: 'Paiement Confirmé',
    processing: 'En Traitement',
    documents_prepared: 'Documents Préparés',
    submitted_to_embassy: 'Soumis à l\'Ambassade',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    cancelled: 'Annulé',
    urgent: 'Traitement Urgent',
    notifications: 'Notifications',
    noNotifications: 'Aucune notification',
    markAsRead: 'Marquer comme lu',
    admin: 'Panneau Admin',
    allApplications: 'Toutes les Demandes',
    pendingReview: 'En Attente de Révision',
    awaitingPayment: 'En Attente de Paiement',
    inProgress: 'En Cours',
    completed: 'Terminé',
    reviewApplication: 'Réviser la Demande',
    confirmPayment: 'Confirmer le Paiement',
    updateStatus: 'Mettre à Jour le Statut',
    addNotes: 'Ajouter des Notes',
    verifyDocuments: 'Vérifier les Documents',
    approve: 'Approuver',
    reject: 'Rejeter',
    downloadDocuments: 'Télécharger les Documents',
    applicantInfo: 'Informations du Demandeur',
    travelInfo: 'Informations de Voyage',
    documents: 'Documents',
    statusHistory: 'Historique des Statuts',
    required: 'Requis',
    optional: 'Optionnel',
    uploadFile: 'Télécharger le Fichier',
    fileUploaded: 'Fichier Téléchargé',
    remove: 'Supprimer',
    language: 'Langue',
    profile: 'Profil',
    settings: 'Paramètres',
    save: 'Enregistrer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    saudiArabia: 'Arabie Saoudite',
    indonesia: 'Indonésie',
    umrahVisa: 'Visa Omra',
    visitVisa: 'Visa de Visite',
    eVisa: 'eVisa',
  },
  ar: {
    appName: 'e-vizza',
    tagline: 'شريكك الموثوق للمساعدة في التأشيرات',
    legalNotice: 'توفر هذه المنصة خدمات مساعدة تأشيرات مستقلة وليست تابعة لأي سلطة حكومية.',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    nationality: 'الجنسية',
    createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    welcome: 'مرحبا',
    dashboard: 'لوحة التحكم',
    newApplication: 'طلب جديد',
    myApplications: 'طلباتي',
    selectCountry: 'اختر بلد الوجهة',
    selectVisaType: 'اختر نوع التأشيرة',
    uploadDocuments: 'تحميل المستندات',
    submit: 'تقديم الطلب',
    cancel: 'إلغاء',
    next: 'التالي',
    back: 'رجوع',
    status: 'الحالة',
    applicationNumber: 'رقم الطلب',
    submittedDate: 'تاريخ التقديم',
    viewDetails: 'عرض التفاصيل',
    draft: 'مسودة',
    submitted: 'مقدم',
    awaiting_payment: 'في انتظار الدفع',
    payment_confirmed: 'تم تأكيد الدفع',
    processing: 'قيد المعالجة',
    documents_prepared: 'تم إعداد المستندات',
    submitted_to_embassy: 'مقدم للسفارة',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    cancelled: 'ملغى',
    urgent: 'معالجة عاجلة',
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    markAsRead: 'وضع علامة كمقروء',
    admin: 'لوحة الإدارة',
    allApplications: 'جميع الطلبات',
    pendingReview: 'قيد المراجعة',
    awaitingPayment: 'في انتظار الدفع',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    reviewApplication: 'مراجعة الطلب',
    confirmPayment: 'تأكيد الدفع',
    updateStatus: 'تحديث الحالة',
    addNotes: 'إضافة ملاحظات',
    verifyDocuments: 'التحقق من المستندات',
    approve: 'موافقة',
    reject: 'رفض',
    downloadDocuments: 'تحميل المستندات',
    applicantInfo: 'معلومات المتقدم',
    travelInfo: 'معلومات السفر',
    documents: 'المستندات',
    statusHistory: 'سجل الحالة',
    required: 'مطلوب',
    optional: 'اختياري',
    uploadFile: 'تحميل الملف',
    fileUploaded: 'تم تحميل الملف',
    remove: 'إزالة',
    language: 'اللغة',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    save: 'حفظ',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    saudiArabia: 'المملكة العربية السعودية',
    indonesia: 'إندونيسيا',
    umrahVisa: 'تأشيرة عمرة',
    visitVisa: 'تأشيرة زيارة',
    eVisa: 'تأشيرة إلكترونية',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
